"""Remove unique constraints

Revision ID: 899c6ccf04dc
Revises: b2cad9d91c3e
Create Date: 2018-05-03 22:01:58.875525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899c6ccf04dc'
down_revision = 'b2cad9d91c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_history_doctor_email', table_name='search_history')
    op.create_index(op.f('ix_search_history_doctor_email'), 'search_history', ['doctor_email'], unique=False)
    op.drop_index('ix_search_history_patient_email', table_name='search_history')
    op.create_index(op.f('ix_search_history_patient_email'), 'search_history', ['patient_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_patient_email'), table_name='search_history')
    op.create_index('ix_search_history_patient_email', 'search_history', ['patient_email'], unique=1)
    op.drop_index(op.f('ix_search_history_doctor_email'), table_name='search_history')
    op.create_index('ix_search_history_doctor_email', 'search_history', ['doctor_email'], unique=1)
    # ### end Alembic commands ###
