"""new table


Revision ID: b2cad9d91c3e
Revises: 5b34c3d39df6
Create Date: 2018-05-03 21:20:08.003291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cad9d91c3e'
down_revision = '5b34c3d39df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=64), nullable=True),
    sa.Column('temperature', sa.String(length=64), nullable=True),
    sa.Column('pressure', sa.String(length=64), nullable=True),
    sa.Column('patient_name', sa.String(length=64), nullable=True),
    sa.Column('doctor_email', sa.String(length=120), nullable=True),
    sa.Column('patient_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_doctor_email'), 'search_history', ['doctor_email'], unique=True)
    op.create_index(op.f('ix_search_history_patient_email'), 'search_history', ['patient_email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_patient_email'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_doctor_email'), table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
